### ISSUE TITLE
pip install pyNmonAnalyzer --user fails. missing README.md

### ISSUE THREAD

**Issue by fovea1959** [madmaze/pyNmonAnalyzer#23]
```
pip install pyNmonAnalyzer --user
Collecting pyNmonAnalyzer
  Using cached pyNmonAnalyzer-1.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-IpqF3P/pyNmonAnalyzer/setup.py", line 23, in <module>
        long_description = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IpqF3P/pyNmonAnalyzer/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by hanzhichao** [comment]
try
`pip install numpy`
`pip install matplotlib` 
first

**Comment by hanzhichao** [comment]
try `git clone https://github.com/madmaze/pyNmonAnalyzer.git`
`cd pyNmonAnalyzer`
and run `python setup install`

**Comment by fovea1959** [comment]
`python setup.py install --user` worked

When will pip install be fixed?

**Comment by madmaze** [comment]
all fixed, sorry for the delay
