### ISSUE TITLE
ModuleNotFoundError: No module named 'pyNmonParser'

### ISSUE THREAD

**Issue by lujun9972** [madmaze/pyNmonAnalyzer#24]
I use pip to install pyNmonAnalyzer matplotlib and numpy like this:
```
(pyNmonAnalyzer) [lujun9972@F31 work]$ pip install pyNmonAnalyzer matplotlib numpy
Collecting pyNmonAnalyzer
  Using cached pyNmonAnalyzer-1.0.8.tar.gz
Collecting matplotlib
  Using cached matplotlib-2.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy
  Using cached numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting six>=1.10 (from matplotlib)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.0 (from matplotlib)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Installing collected packages: pyNmonAnalyzer, six, pyparsing, python-dateutil, cycler, numpy, pytz, matplotlib
  Running setup.py install for pyNmonAnalyzer ... done
Successfully installed cycler-0.10.0 matplotlib-2.1.1 numpy-1.14.0 pyNmonAnalyzer-1.0.8 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.3 six-1.11.0
```
then I try to export the default config like this:
```
(pyNmonAnalyzer) [lujun9972@F31 work]$ pyNmonAnalyzer --defaultConfig
```
There is an error reported:
```
Traceback (most recent call last):
  File "/home/lujun9972/work/pyNmonAnalyzer/bin/pyNmonAnalyzer", line 11, in <module>
    load_entry_point('pyNmonAnalyzer==1.0.8', 'console_scripts', 'pyNmonAnalyzer')()
  File "/home/lujun9972/work/pyNmonAnalyzer/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/lujun9972/work/pyNmonAnalyzer/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/lujun9972/work/pyNmonAnalyzer/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/lujun9972/work/pyNmonAnalyzer/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/lujun9972/work/pyNmonAnalyzer/lib/python3.6/site-packages/pynmonanalyzer/__init__.py", line 18, in <module>
    from pynmonanalyzer import pyNmonAnalyzer as pna
  File "/home/lujun9972/work/pyNmonAnalyzer/lib/python3.6/site-packages/pynmonanalyzer/pyNmonAnalyzer.py", line 25, in <module>
    import pyNmonParser
ModuleNotFoundError: No module named 'pyNmonParser'
```
what is the problem?

I am using python3.6

Thanks

**Comment by madmaze** [comment]
Fixed, I just pushed version 1.0.9
