### ISSUE TITLE
Cannot generate the HTML interactive report file

### ISSUE THREAD

**Issue by aldabrada** [madmaze/pyNmonAnalyzer#25]
Hello,

While using `pyNmonParser -b -o testReport -i test.nmon` I'm getting this error:

INFO - Preparing CSV files..
INFO - Preparing interactive Report..
Traceback (most recent call last):
  File "/usr/local/bin/pyNmonAnalyzer", line 11, in <module>
    sys.exit(pyNmonAnalyzer())
  File "/usr/local/lib/python3.6/dist-packages/pynmonanalyzer/pyNmonAnalyzer.py", line 114, in __init__
    self.processedData, self.args.dygraphLoc)
  File "/usr/local/lib/python3.6/dist-packages/pynmonanalyzer/pyNmonAnalyzer.py", line 308, in buildInteractiveReport
    reportConfig, self.args.outdir, data=data, dygraphLoc=dygraphLoc)
  File "/usr/local/lib/python3.6/dist-packages/pynmonanalyzer/pyNmonReport.py", line 107, in createInteractiveReport
    if max(numericArray) > localMax or localMax == None:
TypeError: '>' not supported between instances of 'float' and 'NoneType'

And while I can see the csv folder and its contents, the interactiveReport.html file is empty (0 Kb) 

Can anyone tell me what could be the the reason behind this error?

**Comment by wsxzhmzwdfxeds** [comment]
change the compare order in pyNmonReport.py line 107:

` if localMax == None or max(numericArray) > localMax:
                            localMax = max(numericArray)
                        if localMin == None or min(numericArray) < localMin:
                            localMin = min(numericArray)
`

**Comment by WuJianyu-CN** [comment]
> change the compare order in pyNmonReport.py line 107:
> 
> `if localMax == None or max(numericArray) > localMax: localMax = max(numericArray) if localMin == None or min(numericArray) < localMin: localMin = min(numericArray)`

It works! Thanks.
